// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvipslspkgbjovgztubb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "LjEkZ03vpVw1PqcnIHgsG5eTqbKhqkD3p2S3TvRpVO8Uc71Yic53f1VrT65rxDvvo1T4Oa6/WvStUURyUoNhpQ==";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);